# version: "3.8"  # Docker Compose file version

services:
  db:  # Service name for PostgreSQL
    image: postgres:15  # Official PostgreSQL image
    restart: always  # Restart the container if it stops
    environment:
      POSTGRES_USER: postgres  # DB username
      POSTGRES_PASSWORD: postgres  # DB password
      POSTGRES_DB: student-performance  # PostgreSQL Database name
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Store DB files persistently
    ports:
      - "5432:5432"  # Host:Container port mapping

  pgadmin:  # UI to manage PostgreSQL
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db  # Start db before this

volumes:
  postgres_data: {}
